platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: latest

inputs:
  - name: source-code

outputs:
  - name: build

params:
  MAVEN_REPO: NOT_SET

run:
  path: "source-code/ci/tasks/package.sh"
#   path: "source-code/gradlew"
#   args: ["--build-file", "source-code/build.gradle", "assemble", "publish"]

# params:
#   TERM: -dumb
#   GRADLE_OPTS: -Dorg.gradle.native=false